DATA:
  RESOLUTION: 512
  CENTER_CROP: True
  RANDOM_FLIP: True
  RANDOM_AUG: True

MODEL:
  NAME: 'CompVis/stable-diffusion-v1-4'

TRAIN:
  EPOCH: 100
  BATCH_SIZE: 4
  LR:
    MODE: 'cosine'
    BASE_LR : 1e-4

EVAL:
  EPOCH: 1
