DATA:
  RESOLUTION: 512
  CENTER_CROP: True
  RANDOM_FLIP: True
  RANDOM_AUG: True

MODEL:
  NAME: 'runwayml/stable-diffusion-v1-5'

TRAIN:
  EPOCH: 40
  BATCH_SIZE: 6
  LR:
    MODE: 'cosine'
    BASE_LR : 1e-4

EVAL:
  EPOCH: 1
