DATA:
  RESOLUTION: 512
  CENTER_CROP: True
  RANDOM_FLIP: True
  RANDOM_AUG: True

MODEL:
  NAME: 'stabilityai/stable-diffusion-2-1'

TRAIN:
  EPOCH: 30
  BATCH_SIZE: 3
  LR:
    MODE: 'cosine'
    BASE_LR : 1e-6

EVAL:
  EPOCH: 1
