DATA:
  RESOLUTION: 768
  CENTER_CROP: True
  RANDOM_FLIP: True
  RANDOM_AUG: True

MODEL:
  NAME: 'stabilityai/stable-diffusion-2-1'

TRAIN:
  EPOCH: 50
  BATCH_SIZE: 2
  LR:
    MODE: 'cosine'
    BASE_LR : 1e-4

EVAL:
  EPOCH: 1
