DATA:
  RESOLUTION: 512
  CENTER_CROP: True
  RANDOM_FLIP: False
  RANDOM_AUG: False

MODEL:
  NAME: 'stabilityai/stable-diffusion-2-1'

TRAIN:
  EPOCH: 10
  BATCH_SIZE: 4
  LR:
    MODE: 'cosine'
    BASE_LR : 1e-6

EVAL:
  EPOCH: 1
