DATA:
  RESOLUTION: 512
  CENTER_CROP: True
  RANDOM_FLIP: False
  RANDOM_AUG: False

MODEL:
  NAME: 'SG161222/Realistic_Vision_V5.1_noVAE'
  VAE: "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors"

TRAIN:
  EPOCH: 10
  BATCH_SIZE: 6
  LR:
    MODE: 'cosine'
    BASE_LR : 1e-6

EVAL:
  EPOCH: 1
